FROM huang/comparative-genomics:20250828

USER root

CMD echo 'Example for Starting Jupyter Notebook on port 30000: jupyter notebook --ip="*" --port=30000 --no-browser --allow-root' && \
    jupyter notebook \
    --ip='*' --port=30000 \
    --no-browser --allow-root
