#!/bin/bash
# BRAKER Quick Test Script (Skip RepeatModeler)
# Generated by 0-ultimate-preprocessing.qmd
#
# WARNING: This script skips repeat masking for QUICK TESTING ONLY!
# Results are NOT suitable for production use.
# Use preprocess_all.sh for the complete pipeline.
#
# Usage: ./braker_quick_test.sh [species_name]
# Example: ./braker_quick_test.sh Anabarilius_grahami
#
set -euo pipefail

# Create test output directory
mkdir -p ./Outputs/Preprocessing/BRAKER_TEST

# Set GeneMark and ProtHint paths (REQUIRED - download manually from http://exon.gatech.edu/GeneMark/license_download.cgi)
# Adjust these paths to match your GeneMark-ETP installation location
GENEMARK_BASE="./Apps/GeneMark-ETP/gmetp_linux_64"

if [ -z "${GENEMARK_PATH:-}" ]; then
    if [ -d "${GENEMARK_BASE}/bin/gmes" ]; then
        export GENEMARK_PATH="$(pwd)/Apps/GeneMark-ETP/gmetp_linux_64/bin/gmes"
        echo "Setting GENEMARK_PATH=$GENEMARK_PATH"
    else
        echo "ERROR: GeneMark-ETP not found!"
        echo ""
        echo "GeneMark requires manual download due to licensing restrictions."
        echo "Please follow these steps:"
        echo "  1. Visit: http://exon.gatech.edu/GeneMark/license_download.cgi"
        echo "  2. Download GeneMark-ETP for Linux 64-bit"
        echo "  3. Extract to ./Apps/GeneMark-ETP/"
        echo "  4. Copy license key: cp ./Apps/GeneMark-ETP/gmetp_linux_64/gm_key_64 ~/.gm_key"
        echo "  5. Re-run this script"
        exit 1
    fi
fi

# Set ProtHint path (bundled with GeneMark-ETP)
if [ -z "${PROTHINT_PATH:-}" ]; then
    if [ -d "${GENEMARK_BASE}/bin/gmes/ProtHint/bin" ]; then
        export PROTHINT_PATH="$(pwd)/Apps/GeneMark-ETP/gmetp_linux_64/bin/gmes/ProtHint/bin"
    elif [ -d "${GENEMARK_BASE}/ProtHint/bin" ]; then
        export PROTHINT_PATH="$(pwd)/Apps/GeneMark-ETP/gmetp_linux_64/ProtHint/bin"
    elif [ -d "./Apps/GeneMark-ETP/ProtHint/bin" ]; then
        export PROTHINT_PATH="$(pwd)/Apps/GeneMark-ETP/ProtHint/bin"
    else
        echo "WARNING: ProtHint not found in expected locations."
        echo "Please check your GeneMark-ETP installation and set PROTHINT_PATH manually."
        exit 1
    fi
    echo "Setting PROTHINT_PATH=$PROTHINT_PATH"
fi

# Select species (default: first species for quick test)
SPECIES="${1:-Anabarilius_grahami}"

echo "========================================"
echo "BRAKER Quick Test (No Repeat Masking)"
echo "Species: $SPECIES"
echo "========================================"
echo ""
echo "WARNING: This is for testing only!"
echo "Production runs should use repeat-masked genomes."
echo ""

case $SPECIES in
    Anabarilius_grahami)
        GENOME="./DB/GENOME_Comparison/Anabarilius_grahami/ncbi_dataset/data/GCA_003731715.1/GCA_003731715.1_BGI_Agra_1.0_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Anabarilius_grahami"
        ;;
    Aspiorhynchus_laticeps)
        GENOME="./DB/GENOME_Comparison/Aspiorhynchus_laticeps/ncbi_dataset/data/GCA_023376895.1/GCA_023376895.1_ASM2337689v1_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Aspiorhynchus_laticeps"
        ;;
    Carassius_auratus)
        GENOME="./DB/GENOME_Comparison/Carassius_auratus/ncbi_dataset/data/GCA_003368295.1/GCA_003368295.1_ASM336829v1_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Carassius_auratus"
        ;;
    Cyprinus_carpio)
        GENOME="./DB/GENOME_Comparison/Cyprinus_carpio/ncbi_dataset/data/GCF_018340385.1/GCF_018340385.1_ASM1834038v1_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Cyprinus_carpio"
        ;;
    Danio_rerio)
        GENOME="./DB/GENOME_Comparison/Danio_rerio/ncbi_dataset/data/GCF_000002035.6/GCF_000002035.6_GRCz11_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Danio_rerio"
        ;;
    Gymnocypris_eckloni)
        GENOME="./DB/GENOME_Comparison/Gymnocypris_eckloni/ncbi_dataset/data/GCA_027564155.1/GCA_027564155.1_ASM2756415v1_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Gymnocypris_eckloni"
        ;;
    Labeo_rohita)
        GENOME="./DB/GENOME_Comparison/Labeo_rohita/ncbi_dataset/data/GCA_022985175.1/GCA_022985175.1_IGBB_LRoh.1.0_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Labeo_rohita"
        ;;
    Onychostoma_macrolepis)
        GENOME="./DB/GENOME_Comparison/Onychostoma_macrolepis/ncbi_dataset/data/GCA_012432095.1/GCA_012432095.1_ASM1243209v1_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Onychostoma_macrolepis"
        ;;
    Oxygymnocypris_stewartii)
        GENOME="./DB/GENOME_Comparison/Oxygymnocypris_stewartii/ncbi_dataset/data/GCA_003573665.1/GCA_003573665.1_Novo_Ost_1.0_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Oxygymnocypris_stewartii"
        ;;
    Schizothorax_macropogon)
        GENOME="./DB/GENOME_Comparison/Schizothorax_macropogon/ncbi_dataset/data/GCA_041051915.1/GCA_041051915.1_ASM4105191v1_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Schizothorax_macropogon"
        ;;
    Sinocyclocheilus_grahami)
        GENOME="./DB/GENOME_Comparison/Sinocyclocheilus_grahami/ncbi_dataset/data/GCA_001515645.1/GCA_001515645.1_SAMN03320097.WGS_v1.1_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Sinocyclocheilus_grahami"
        ;;
    Triplophysa_bombifrons)
        GENOME="./DB/GENOME_Comparison/Triplophysa_bombifrons/ncbi_dataset/data/GCA_029783895.1/GCA_029783895.1_ASM2978389v1_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Triplophysa_bombifrons"
        ;;
    Triplophysa_dalaica)
        GENOME="./DB/GENOME_Comparison/Triplophysa_dalaica/ncbi_dataset/data/GCA_015846415.1/GCA_015846415.1_ASM1584641v1_genomic.fna"
        OUTDIR="./Outputs/Preprocessing/BRAKER_TEST/Triplophysa_dalaica"
        ;;
    *)
        echo "Unknown species: $SPECIES"
        echo "Available species:"
        echo "  - Anabarilius_grahami"
        echo "  - Aspiorhynchus_laticeps"
        echo "  - Carassius_auratus"
        echo "  - Cyprinus_carpio"
        echo "  - Danio_rerio"
        echo "  - Gymnocypris_eckloni"
        echo "  - Labeo_rohita"
        echo "  - Onychostoma_macrolepis"
        echo "  - Oxygymnocypris_stewartii"
        echo "  - Schizothorax_macropogon"
        echo "  - Sinocyclocheilus_grahami"
        echo "  - Triplophysa_bombifrons"
        echo "  - Triplophysa_dalaica"
        exit 1
        ;;
esac

mkdir -p "$OUTDIR"

echo "Running BRAKER test on: $GENOME"
echo "Output directory: $OUTDIR"
echo ""

conda run -n braker3_env braker.pl \
    --genome="$GENOME" \
    --prot_seq=./DB/Metazoa.fa \
    --species="${SPECIES}_test" \
    --threads=16 \
    --gff3 \
    --workingdir="$OUTDIR"

echo ""
echo "========================================"
echo "Quick test completed!"
echo "Check results in: $OUTDIR"
echo "========================================"
