#!/bin/bash
# Genome Preprocessing Pipeline
# Generated by 0-ultimate-preprocessing.qmd
set -euo pipefail


# ============================================================
# Anabarilius_grahami
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Anabarilius_grahami/Anabarilius_grahami_db ./DB/GENOME_Comparison/Anabarilius_grahami/ncbi_dataset/data/GCA_003731715.1/GCA_003731715.1_BGI_Agra_1.0_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Anabarilius_grahami/Anabarilius_grahami_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Anabarilius_grahami/Anabarilius_grahami_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Anabarilius_grahami ./DB/GENOME_Comparison/Anabarilius_grahami/ncbi_dataset/data/GCA_003731715.1/GCA_003731715.1_BGI_Agra_1.0_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Anabarilius_grahami/GCA_003731715.1_BGI_Agra_1.0_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Anabarilius_grahami --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Anabarilius_grahami

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Anabarilius_grahami/ncbi_dataset/data/GCA_003731715.1/GCA_003731715.1_BGI_Agra_1.0_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Anabarilius_grahami_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Anabarilius_grahami

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Anabarilius_grahami/braker.aa ./Outputs/Preprocessing/BRAKER/Anabarilius_grahami/Anabarilius_grahami_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Anabarilius_grahami/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Anabarilius_grahami/Anabarilius_grahami_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Anabarilius_grahami/Anabarilius_grahami_proteins.faa -l actinopterygii_odb12 -m protein -o Anabarilius_grahami_busco --out_path ./Outputs/Preprocessing/BUSCO/Anabarilius_grahami -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Anabarilius_grahami/Anabarilius_grahami_proteins.faa -l actinopterygii_odb12 -m protein -o Anabarilius_grahami_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Anabarilius_grahami -c 8


# ============================================================
# Aspiorhynchus_laticeps
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Aspiorhynchus_laticeps/Aspiorhynchus_laticeps_db ./DB/GENOME_Comparison/Aspiorhynchus_laticeps/ncbi_dataset/data/GCA_023376895.1/GCA_023376895.1_ASM2337689v1_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Aspiorhynchus_laticeps/Aspiorhynchus_laticeps_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Aspiorhynchus_laticeps/Aspiorhynchus_laticeps_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Aspiorhynchus_laticeps ./DB/GENOME_Comparison/Aspiorhynchus_laticeps/ncbi_dataset/data/GCA_023376895.1/GCA_023376895.1_ASM2337689v1_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Aspiorhynchus_laticeps/GCA_023376895.1_ASM2337689v1_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Aspiorhynchus_laticeps --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Aspiorhynchus_laticeps

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Aspiorhynchus_laticeps/ncbi_dataset/data/GCA_023376895.1/GCA_023376895.1_ASM2337689v1_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Aspiorhynchus_laticeps_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Aspiorhynchus_laticeps

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Aspiorhynchus_laticeps/braker.aa ./Outputs/Preprocessing/BRAKER/Aspiorhynchus_laticeps/Aspiorhynchus_laticeps_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Aspiorhynchus_laticeps/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Aspiorhynchus_laticeps/Aspiorhynchus_laticeps_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Aspiorhynchus_laticeps/Aspiorhynchus_laticeps_proteins.faa -l actinopterygii_odb12 -m protein -o Aspiorhynchus_laticeps_busco --out_path ./Outputs/Preprocessing/BUSCO/Aspiorhynchus_laticeps -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Aspiorhynchus_laticeps/Aspiorhynchus_laticeps_proteins.faa -l actinopterygii_odb12 -m protein -o Aspiorhynchus_laticeps_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Aspiorhynchus_laticeps -c 8


# ============================================================
# Carassius_auratus
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Carassius_auratus/Carassius_auratus_db ./DB/GENOME_Comparison/Carassius_auratus/ncbi_dataset/data/GCA_003368295.1/GCA_003368295.1_ASM336829v1_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Carassius_auratus/Carassius_auratus_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Carassius_auratus/Carassius_auratus_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Carassius_auratus ./DB/GENOME_Comparison/Carassius_auratus/ncbi_dataset/data/GCA_003368295.1/GCA_003368295.1_ASM336829v1_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Carassius_auratus/GCA_003368295.1_ASM336829v1_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Carassius_auratus --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Carassius_auratus

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Carassius_auratus/ncbi_dataset/data/GCA_003368295.1/GCA_003368295.1_ASM336829v1_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Carassius_auratus_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Carassius_auratus

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Carassius_auratus/braker.aa ./Outputs/Preprocessing/BRAKER/Carassius_auratus/Carassius_auratus_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Carassius_auratus/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Carassius_auratus/Carassius_auratus_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Carassius_auratus/Carassius_auratus_proteins.faa -l actinopterygii_odb12 -m protein -o Carassius_auratus_busco --out_path ./Outputs/Preprocessing/BUSCO/Carassius_auratus -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Carassius_auratus/Carassius_auratus_proteins.faa -l actinopterygii_odb12 -m protein -o Carassius_auratus_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Carassius_auratus -c 8


# ============================================================
# Cyprinus_carpio
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Cyprinus_carpio/Cyprinus_carpio_db ./DB/GENOME_Comparison/Cyprinus_carpio/ncbi_dataset/data/GCF_018340385.1/GCF_018340385.1_ASM1834038v1_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Cyprinus_carpio/Cyprinus_carpio_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Cyprinus_carpio/Cyprinus_carpio_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Cyprinus_carpio ./DB/GENOME_Comparison/Cyprinus_carpio/ncbi_dataset/data/GCF_018340385.1/GCF_018340385.1_ASM1834038v1_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Cyprinus_carpio/GCF_018340385.1_ASM1834038v1_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Cyprinus_carpio --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Cyprinus_carpio

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Cyprinus_carpio/ncbi_dataset/data/GCF_018340385.1/GCF_018340385.1_ASM1834038v1_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Cyprinus_carpio_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Cyprinus_carpio

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Cyprinus_carpio/braker.aa ./Outputs/Preprocessing/BRAKER/Cyprinus_carpio/Cyprinus_carpio_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Cyprinus_carpio/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Cyprinus_carpio/Cyprinus_carpio_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Cyprinus_carpio/Cyprinus_carpio_proteins.faa -l actinopterygii_odb12 -m protein -o Cyprinus_carpio_busco --out_path ./Outputs/Preprocessing/BUSCO/Cyprinus_carpio -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Cyprinus_carpio/Cyprinus_carpio_proteins.faa -l actinopterygii_odb12 -m protein -o Cyprinus_carpio_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Cyprinus_carpio -c 8


# ============================================================
# Danio_rerio
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Danio_rerio/Danio_rerio_db ./DB/GENOME_Comparison/Danio_rerio/ncbi_dataset/data/GCF_000002035.6/GCF_000002035.6_GRCz11_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Danio_rerio/Danio_rerio_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Danio_rerio/Danio_rerio_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Danio_rerio ./DB/GENOME_Comparison/Danio_rerio/ncbi_dataset/data/GCF_000002035.6/GCF_000002035.6_GRCz11_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Danio_rerio/GCF_000002035.6_GRCz11_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Danio_rerio --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Danio_rerio

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Danio_rerio/ncbi_dataset/data/GCF_000002035.6/GCF_000002035.6_GRCz11_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Danio_rerio_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Danio_rerio

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Danio_rerio/braker.aa ./Outputs/Preprocessing/BRAKER/Danio_rerio/Danio_rerio_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Danio_rerio/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Danio_rerio/Danio_rerio_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Danio_rerio/Danio_rerio_proteins.faa -l actinopterygii_odb12 -m protein -o Danio_rerio_busco --out_path ./Outputs/Preprocessing/BUSCO/Danio_rerio -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Danio_rerio/Danio_rerio_proteins.faa -l actinopterygii_odb12 -m protein -o Danio_rerio_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Danio_rerio -c 8


# ============================================================
# Gymnocypris_eckloni
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Gymnocypris_eckloni/Gymnocypris_eckloni_db ./DB/GENOME_Comparison/Gymnocypris_eckloni/ncbi_dataset/data/GCA_027564155.1/GCA_027564155.1_ASM2756415v1_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Gymnocypris_eckloni/Gymnocypris_eckloni_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Gymnocypris_eckloni/Gymnocypris_eckloni_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Gymnocypris_eckloni ./DB/GENOME_Comparison/Gymnocypris_eckloni/ncbi_dataset/data/GCA_027564155.1/GCA_027564155.1_ASM2756415v1_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Gymnocypris_eckloni/GCA_027564155.1_ASM2756415v1_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Gymnocypris_eckloni --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Gymnocypris_eckloni

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Gymnocypris_eckloni/ncbi_dataset/data/GCA_027564155.1/GCA_027564155.1_ASM2756415v1_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Gymnocypris_eckloni_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Gymnocypris_eckloni

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Gymnocypris_eckloni/braker.aa ./Outputs/Preprocessing/BRAKER/Gymnocypris_eckloni/Gymnocypris_eckloni_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Gymnocypris_eckloni/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Gymnocypris_eckloni/Gymnocypris_eckloni_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Gymnocypris_eckloni/Gymnocypris_eckloni_proteins.faa -l actinopterygii_odb12 -m protein -o Gymnocypris_eckloni_busco --out_path ./Outputs/Preprocessing/BUSCO/Gymnocypris_eckloni -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Gymnocypris_eckloni/Gymnocypris_eckloni_proteins.faa -l actinopterygii_odb12 -m protein -o Gymnocypris_eckloni_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Gymnocypris_eckloni -c 8


# ============================================================
# Labeo_rohita
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Labeo_rohita/Labeo_rohita_db ./DB/GENOME_Comparison/Labeo_rohita/ncbi_dataset/data/GCA_022985175.1/GCA_022985175.1_IGBB_LRoh.1.0_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Labeo_rohita/Labeo_rohita_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Labeo_rohita/Labeo_rohita_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Labeo_rohita ./DB/GENOME_Comparison/Labeo_rohita/ncbi_dataset/data/GCA_022985175.1/GCA_022985175.1_IGBB_LRoh.1.0_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Labeo_rohita/GCA_022985175.1_IGBB_LRoh.1.0_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Labeo_rohita --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Labeo_rohita

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Labeo_rohita/ncbi_dataset/data/GCA_022985175.1/GCA_022985175.1_IGBB_LRoh.1.0_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Labeo_rohita_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Labeo_rohita

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Labeo_rohita/braker.aa ./Outputs/Preprocessing/BRAKER/Labeo_rohita/Labeo_rohita_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Labeo_rohita/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Labeo_rohita/Labeo_rohita_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Labeo_rohita/Labeo_rohita_proteins.faa -l actinopterygii_odb12 -m protein -o Labeo_rohita_busco --out_path ./Outputs/Preprocessing/BUSCO/Labeo_rohita -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Labeo_rohita/Labeo_rohita_proteins.faa -l actinopterygii_odb12 -m protein -o Labeo_rohita_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Labeo_rohita -c 8


# ============================================================
# Onychostoma_macrolepis
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Onychostoma_macrolepis/Onychostoma_macrolepis_db ./DB/GENOME_Comparison/Onychostoma_macrolepis/ncbi_dataset/data/GCA_012432095.1/GCA_012432095.1_ASM1243209v1_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Onychostoma_macrolepis/Onychostoma_macrolepis_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Onychostoma_macrolepis/Onychostoma_macrolepis_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Onychostoma_macrolepis ./DB/GENOME_Comparison/Onychostoma_macrolepis/ncbi_dataset/data/GCA_012432095.1/GCA_012432095.1_ASM1243209v1_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Onychostoma_macrolepis/GCA_012432095.1_ASM1243209v1_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Onychostoma_macrolepis --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Onychostoma_macrolepis

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Onychostoma_macrolepis/ncbi_dataset/data/GCA_012432095.1/GCA_012432095.1_ASM1243209v1_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Onychostoma_macrolepis_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Onychostoma_macrolepis

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Onychostoma_macrolepis/braker.aa ./Outputs/Preprocessing/BRAKER/Onychostoma_macrolepis/Onychostoma_macrolepis_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Onychostoma_macrolepis/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Onychostoma_macrolepis/Onychostoma_macrolepis_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Onychostoma_macrolepis/Onychostoma_macrolepis_proteins.faa -l actinopterygii_odb12 -m protein -o Onychostoma_macrolepis_busco --out_path ./Outputs/Preprocessing/BUSCO/Onychostoma_macrolepis -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Onychostoma_macrolepis/Onychostoma_macrolepis_proteins.faa -l actinopterygii_odb12 -m protein -o Onychostoma_macrolepis_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Onychostoma_macrolepis -c 8


# ============================================================
# Oxygymnocypris_stewartii
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Oxygymnocypris_stewartii/Oxygymnocypris_stewartii_db ./DB/GENOME_Comparison/Oxygymnocypris_stewartii/ncbi_dataset/data/GCA_003573665.1/GCA_003573665.1_Novo_Ost_1.0_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Oxygymnocypris_stewartii/Oxygymnocypris_stewartii_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Oxygymnocypris_stewartii/Oxygymnocypris_stewartii_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Oxygymnocypris_stewartii ./DB/GENOME_Comparison/Oxygymnocypris_stewartii/ncbi_dataset/data/GCA_003573665.1/GCA_003573665.1_Novo_Ost_1.0_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Oxygymnocypris_stewartii/GCA_003573665.1_Novo_Ost_1.0_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Oxygymnocypris_stewartii --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Oxygymnocypris_stewartii

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Oxygymnocypris_stewartii/ncbi_dataset/data/GCA_003573665.1/GCA_003573665.1_Novo_Ost_1.0_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Oxygymnocypris_stewartii_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Oxygymnocypris_stewartii

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Oxygymnocypris_stewartii/braker.aa ./Outputs/Preprocessing/BRAKER/Oxygymnocypris_stewartii/Oxygymnocypris_stewartii_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Oxygymnocypris_stewartii/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Oxygymnocypris_stewartii/Oxygymnocypris_stewartii_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Oxygymnocypris_stewartii/Oxygymnocypris_stewartii_proteins.faa -l actinopterygii_odb12 -m protein -o Oxygymnocypris_stewartii_busco --out_path ./Outputs/Preprocessing/BUSCO/Oxygymnocypris_stewartii -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Oxygymnocypris_stewartii/Oxygymnocypris_stewartii_proteins.faa -l actinopterygii_odb12 -m protein -o Oxygymnocypris_stewartii_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Oxygymnocypris_stewartii -c 8


# ============================================================
# Schizothorax_macropogon
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Schizothorax_macropogon/Schizothorax_macropogon_db ./DB/GENOME_Comparison/Schizothorax_macropogon/ncbi_dataset/data/GCA_041051915.1/GCA_041051915.1_ASM4105191v1_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Schizothorax_macropogon/Schizothorax_macropogon_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Schizothorax_macropogon/Schizothorax_macropogon_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Schizothorax_macropogon ./DB/GENOME_Comparison/Schizothorax_macropogon/ncbi_dataset/data/GCA_041051915.1/GCA_041051915.1_ASM4105191v1_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Schizothorax_macropogon/GCA_041051915.1_ASM4105191v1_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Schizothorax_macropogon --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Schizothorax_macropogon

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Schizothorax_macropogon/ncbi_dataset/data/GCA_041051915.1/GCA_041051915.1_ASM4105191v1_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Schizothorax_macropogon_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Schizothorax_macropogon

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Schizothorax_macropogon/braker.aa ./Outputs/Preprocessing/BRAKER/Schizothorax_macropogon/Schizothorax_macropogon_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Schizothorax_macropogon/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Schizothorax_macropogon/Schizothorax_macropogon_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Schizothorax_macropogon/Schizothorax_macropogon_proteins.faa -l actinopterygii_odb12 -m protein -o Schizothorax_macropogon_busco --out_path ./Outputs/Preprocessing/BUSCO/Schizothorax_macropogon -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Schizothorax_macropogon/Schizothorax_macropogon_proteins.faa -l actinopterygii_odb12 -m protein -o Schizothorax_macropogon_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Schizothorax_macropogon -c 8


# ============================================================
# Sinocyclocheilus_grahami
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Sinocyclocheilus_grahami/Sinocyclocheilus_grahami_db ./DB/GENOME_Comparison/Sinocyclocheilus_grahami/ncbi_dataset/data/GCA_001515645.1/GCA_001515645.1_SAMN03320097.WGS_v1.1_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Sinocyclocheilus_grahami/Sinocyclocheilus_grahami_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Sinocyclocheilus_grahami/Sinocyclocheilus_grahami_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Sinocyclocheilus_grahami ./DB/GENOME_Comparison/Sinocyclocheilus_grahami/ncbi_dataset/data/GCA_001515645.1/GCA_001515645.1_SAMN03320097.WGS_v1.1_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Sinocyclocheilus_grahami/GCA_001515645.1_SAMN03320097.WGS_v1.1_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Sinocyclocheilus_grahami --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Sinocyclocheilus_grahami

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Sinocyclocheilus_grahami/ncbi_dataset/data/GCA_001515645.1/GCA_001515645.1_SAMN03320097.WGS_v1.1_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Sinocyclocheilus_grahami_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Sinocyclocheilus_grahami

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Sinocyclocheilus_grahami/braker.aa ./Outputs/Preprocessing/BRAKER/Sinocyclocheilus_grahami/Sinocyclocheilus_grahami_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Sinocyclocheilus_grahami/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Sinocyclocheilus_grahami/Sinocyclocheilus_grahami_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Sinocyclocheilus_grahami/Sinocyclocheilus_grahami_proteins.faa -l actinopterygii_odb12 -m protein -o Sinocyclocheilus_grahami_busco --out_path ./Outputs/Preprocessing/BUSCO/Sinocyclocheilus_grahami -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Sinocyclocheilus_grahami/Sinocyclocheilus_grahami_proteins.faa -l actinopterygii_odb12 -m protein -o Sinocyclocheilus_grahami_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Sinocyclocheilus_grahami -c 8


# ============================================================
# Triplophysa_bombifrons
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Triplophysa_bombifrons/Triplophysa_bombifrons_db ./DB/GENOME_Comparison/Triplophysa_bombifrons/ncbi_dataset/data/GCA_029783895.1/GCA_029783895.1_ASM2978389v1_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Triplophysa_bombifrons/Triplophysa_bombifrons_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Triplophysa_bombifrons/Triplophysa_bombifrons_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Triplophysa_bombifrons ./DB/GENOME_Comparison/Triplophysa_bombifrons/ncbi_dataset/data/GCA_029783895.1/GCA_029783895.1_ASM2978389v1_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Triplophysa_bombifrons/GCA_029783895.1_ASM2978389v1_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Triplophysa_bombifrons --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Triplophysa_bombifrons

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Triplophysa_bombifrons/ncbi_dataset/data/GCA_029783895.1/GCA_029783895.1_ASM2978389v1_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Triplophysa_bombifrons_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Triplophysa_bombifrons

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Triplophysa_bombifrons/braker.aa ./Outputs/Preprocessing/BRAKER/Triplophysa_bombifrons/Triplophysa_bombifrons_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Triplophysa_bombifrons/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Triplophysa_bombifrons/Triplophysa_bombifrons_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Triplophysa_bombifrons/Triplophysa_bombifrons_proteins.faa -l actinopterygii_odb12 -m protein -o Triplophysa_bombifrons_busco --out_path ./Outputs/Preprocessing/BUSCO/Triplophysa_bombifrons -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Triplophysa_bombifrons/Triplophysa_bombifrons_proteins.faa -l actinopterygii_odb12 -m protein -o Triplophysa_bombifrons_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Triplophysa_bombifrons -c 8


# ============================================================
# Triplophysa_dalaica
# ============================================================

# 1_build_db
conda run -n genome_annotation_env BuildDatabase -name ./Outputs/Preprocessing/RepeatModeler/Triplophysa_dalaica/Triplophysa_dalaica_db ./DB/GENOME_Comparison/Triplophysa_dalaica/ncbi_dataset/data/GCA_015846415.1/GCA_015846415.1_ASM1584641v1_genomic.fna

# 2_repeat_modeler
conda run -n genome_annotation_env RepeatModeler -database ./Outputs/Preprocessing/RepeatModeler/Triplophysa_dalaica/Triplophysa_dalaica_db -threads 8 -engine ncbi

# 3_repeat_masker
conda run -n genome_annotation_env RepeatMasker -lib ./Outputs/Preprocessing/RepeatModeler/Triplophysa_dalaica/Triplophysa_dalaica_db-families.fa -xsmall -pa 8 -dir ./Outputs/Preprocessing/RepeatMasker/Triplophysa_dalaica ./DB/GENOME_Comparison/Triplophysa_dalaica/ncbi_dataset/data/GCA_015846415.1/GCA_015846415.1_ASM1584641v1_genomic.fna

# 4_braker
# NOTE: BRAKER with repeat-masked genome (production quality)
conda run -n braker3_env braker.pl --genome=./Outputs/Preprocessing/RepeatMasker/Triplophysa_dalaica/GCA_015846415.1_ASM1584641v1_genomic.fna.masked --prot_seq=./DB/Metazoa.fa --species=Triplophysa_dalaica --softmasking --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER/Triplophysa_dalaica

# 4.5_braker_unmasked
# NOTE: BRAKER with original unmasked genome (for comparison)
conda run -n braker3_env braker.pl --genome=./DB/GENOME_Comparison/Triplophysa_dalaica/ncbi_dataset/data/GCA_015846415.1/GCA_015846415.1_ASM1584641v1_genomic.fna --prot_seq=./DB/Metazoa.fa --species=Triplophysa_dalaica_unmasked --threads=8 --gff3 --workingdir=./Outputs/Preprocessing/BRAKER_UNMASKED/Triplophysa_dalaica

# 5_copy_proteins
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER/Triplophysa_dalaica/braker.aa ./Outputs/Preprocessing/BRAKER/Triplophysa_dalaica/Triplophysa_dalaica_proteins.faa

# 5.5_copy_proteins_unmasked
# NOTE: Copy BRAKER protein output (avoids gffread ID mismatch issues)
cp ./Outputs/Preprocessing/BRAKER_UNMASKED/Triplophysa_dalaica/braker.aa ./Outputs/Preprocessing/BRAKER_UNMASKED/Triplophysa_dalaica/Triplophysa_dalaica_proteins.faa

# 6_busco
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER/Triplophysa_dalaica/Triplophysa_dalaica_proteins.faa -l actinopterygii_odb12 -m protein -o Triplophysa_dalaica_busco --out_path ./Outputs/Preprocessing/BUSCO/Triplophysa_dalaica -c 8

# 6.5_busco_unmasked
conda run -n genome_annotation_env busco -i ./Outputs/Preprocessing/BRAKER_UNMASKED/Triplophysa_dalaica/Triplophysa_dalaica_proteins.faa -l actinopterygii_odb12 -m protein -o Triplophysa_dalaica_unmasked_busco --out_path ./Outputs/Preprocessing/BUSCO_UNMASKED/Triplophysa_dalaica -c 8

